"""Version checking, PyPI queries, auto-upgrade, revert, global state."""

from __future__ import annotations

import contextlib
import json as json_mod
import logging
import re
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any
from urllib.request import Request, urlopen

if TYPE_CHECKING:
    from collections.abc import Iterator

import click
import yaml

from mcp_synology import __version__

logger = logging.getLogger(__name__)

_PYPI_PACKAGE = "mcp-synology"
_VERSION_CHECK_INTERVAL = 86400  # 24 hours

# Loose PEP 440-ish: requires X.Y.Z and optionally trailing pre/post/dev/local
# segments separated by `-` or `.` (e.g. `0.5.1`, `0.5.1-rc1`, `1.2.3.post4`).
# Tight enough to reject `latest`, `1.2`, whitespace, or shell metacharacters
# before the value reaches `pip install mcp-synology==<value>`.
_VERSION_RE = re.compile(r"^\d+\.\d+\.\d+([-.]?[a-zA-Z0-9]+)*$")


def _validate_version_string(value: str) -> None:
    """Reject malformed version strings before they flow into a pip command.

    Raises click.ClickException so click renders the standard `Error: ...`
    line and exits 1 — same shape as the other CLI error paths.
    """
    if not isinstance(value, str) or not _VERSION_RE.match(value):
        raise click.ClickException(
            f"Invalid version string: {value!r}. "
            "Expected MAJOR.MINOR.PATCH with optional pre/post suffix "
            "(e.g. 0.5.1, 0.5.1-rc1, 1.2.3.post4)."
        )


def _get_current_version() -> str:
    """Return the running version."""
    try:
        from importlib.metadata import PackageNotFoundError
        from importlib.metadata import version as _pkg_version

        return _pkg_version(_PYPI_PACKAGE)
    except (PackageNotFoundError, ImportError):
        return __version__


def _get_latest_pypi_version() -> str | None:
    """Fetch the latest version from PyPI. Returns None on any failure."""
    try:
        req = Request(
            f"https://pypi.org/pypi/{_PYPI_PACKAGE}/json",
            headers={"User-Agent": f"{_PYPI_PACKAGE}/{_get_current_version()}"},
        )
        with urlopen(req, timeout=5) as resp:
            data = json_mod.loads(resp.read())
        result: str = data["info"]["version"]
        return result
    except (OSError, KeyError, ValueError):
        return None


def _version_tuple(v: str) -> tuple[int, ...] | None:
    """Parse a `MAJOR.MINOR.PATCH` string into a comparable tuple.

    Returns None on parse failure (non-numeric segments, missing pieces, etc.)
    so callers must explicitly handle the case rather than have a `(0,)`
    sentinel silently compare less than every real version.
    """
    try:
        return tuple(int(x) for x in v.split("."))
    except (ValueError, AttributeError):
        logger.debug("_version_tuple: failed to parse %r", v)
        return None


def _detect_installer() -> str | None:
    """Detect whether the tool was installed via uv tool or pipx."""
    import shutil

    bin_path = shutil.which(_PYPI_PACKAGE) or ""
    if "uv" in bin_path and "tools" in bin_path:
        return "uv"
    if "pipx" in bin_path:
        return "pipx"
    return None


def _global_state_path() -> Path:
    return Path.home() / ".local" / "state" / "mcp-synology" / "global.yaml"


def _load_global_state() -> dict[str, Any]:
    """Load global (non-instance) state for version tracking."""
    path = _global_state_path()
    if not path.exists():
        return {}
    try:
        raw: dict[str, Any] = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        return raw
    except (OSError, yaml.YAMLError):
        return {}


def _save_global_state(state: dict[str, Any]) -> None:
    """Save global state atomically."""
    from mcp_synology.core.fs import atomic_write_text

    raw_text = yaml.dump(state, default_flow_style=False, sort_keys=False)
    atomic_write_text(_global_state_path(), "# Auto-generated by mcp-synology.\n" + raw_text)


@contextlib.contextmanager
def _with_global_state_lock() -> Iterator[None]:
    """Hold an exclusive lock around a load → mutate → save sequence on global.yaml.

    Save-side atomicity (`atomic_write_text` from PR #69) prevents torn writes,
    but the read-modify-write sequence has no inter-process synchronization. Two
    callers can each load the file, mutate distinct keys, then save atomically —
    and the later writer's update overwrites the earlier writer's because each
    computed its new state from a stale read. The lock spans the whole critical
    section so callers (not the save function) hold it.

    Windows lacks `fcntl`; fall through with no locking. The practical risk
    surface is single-user dev boxes (per #93).
    """
    if sys.platform == "win32":
        yield
        return

    import fcntl

    lock_dir = _global_state_path().parent
    lock_dir.mkdir(parents=True, exist_ok=True)
    lock_path = lock_dir / "global.yaml.lock"
    with lock_path.open("a+") as fh:
        fcntl.flock(fh.fileno(), fcntl.LOCK_EX)
        try:
            yield
        finally:
            fcntl.flock(fh.fileno(), fcntl.LOCK_UN)


def _check_for_update(state: dict[str, Any], *, force: bool = False) -> str | None:
    """Check PyPI for a newer version. Returns latest version string if newer, else None."""
    now = datetime.now(tz=UTC).timestamp()
    if not force:
        last = state.get("last_version_check")
        if last:
            try:
                elapsed = now - datetime.fromisoformat(last).timestamp()
                if elapsed < _VERSION_CHECK_INTERVAL:
                    latest: str | None = state.get("latest_known_version")
                    current = _get_current_version()
                    if latest:
                        latest_t = _version_tuple(latest)
                        current_t = _version_tuple(current)
                        if latest_t is not None and current_t is not None and latest_t > current_t:
                            return latest
                    return None
            except (ValueError, TypeError, AttributeError):
                pass

    latest = _get_latest_pypi_version()
    state["last_version_check"] = datetime.now(tz=UTC).isoformat()
    if not latest:
        return None

    state["latest_known_version"] = latest
    current = _get_current_version()

    latest_t = _version_tuple(latest)
    current_t = _version_tuple(current)
    if latest_t is not None and current_t is not None and latest_t > current_t:
        return latest
    return None


def _do_auto_upgrade() -> bool:
    """Upgrade to the latest version. Returns True on success."""
    installer = _detect_installer()
    current = _get_current_version()

    if installer == "uv":
        cmd = ["uv", "tool", "install", f"{_PYPI_PACKAGE}@latest"]
    elif installer == "pipx":
        cmd = ["pipx", "upgrade", _PYPI_PACKAGE]
    else:
        click.echo(
            "Cannot detect package manager (uv or pipx). "
            f"Upgrade manually: uv tool upgrade {_PYPI_PACKAGE}"
        )
        return False

    click.echo(f"Upgrading {_PYPI_PACKAGE} via {installer}...")
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode == 0:
        with _with_global_state_lock():
            state = _load_global_state()
            state["previous_version"] = current
            _save_global_state(state)
        click.echo(click.style("Upgrade complete — takes effect on next run.", fg="green"))
        return True
    click.echo(click.style(f"Upgrade failed: {result.stderr.strip()}", fg="red"), err=True)
    return False


def _do_revert(target_version: str | None = None) -> None:
    """Revert to a specific version or the previously recorded one."""
    state = _load_global_state()
    current = _get_current_version()

    prev: str | None
    if target_version:
        prev = target_version
    else:
        prev = state.get("previous_version")
        if not prev:
            click.echo("No previous version recorded — nothing to revert to.")
            click.echo(f"Tip: specify a version explicitly: {_PYPI_PACKAGE} --revert 0.1.0")
            return

    _validate_version_string(prev)

    if prev == current:
        click.echo(f"Already running {current} — nothing to do.")
        return

    installer = _detect_installer()

    if installer == "uv":
        cmd = ["uv", "tool", "install", "--force", f"{_PYPI_PACKAGE}=={prev}"]
    elif installer == "pipx":
        cmd = ["pipx", "install", "--force", f"{_PYPI_PACKAGE}=={prev}"]
    else:
        click.echo(
            f"Cannot detect package manager. Install manually:\n"
            f"  uv tool install --force {_PYPI_PACKAGE}=={prev}\n"
            f"  pipx install --force {_PYPI_PACKAGE}=={prev}"
        )
        return

    click.echo(f"Reverting from {current} to {prev}...")
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode == 0:
        with _with_global_state_lock():
            fresh = _load_global_state()
            fresh["previous_version"] = None
            fresh["auto_upgrade"] = False
            _save_global_state(fresh)
        click.echo(click.style(f"Reverted to {prev}. Takes effect on next run.", fg="green"))
        click.echo("Auto-upgrade has been disabled to prevent immediately re-upgrading.")
        click.echo(f"Re-enable with: {_PYPI_PACKAGE} --auto-upgrade enable")
    else:
        click.echo(click.style(f"Revert failed: {result.stderr.strip()}", fg="red"), err=True)
